### PR TITLE
Add argument parsing [unitaryHACK]

### LINKED ISSUE #123: qcor api for argument parsing
It would be nice to provide a public API for qcor programmers to specify expected command line arguments. Could delegate to something like https://github.com/p-ranav/argparse

### PR DESCRIPTION
**Pull request by amirebrahimi**
Resolves #123 

I'm not that familiar with cmake, but I tried to match as much of the convention that XACC uses with third party libraries. 

There are two ways this can be used:
### Explicitly
```C
__qpu__ void f(qreg q) {
  H(q);
  Measure(q);
}

int main(int argc, char** argv) {
    ArgumentParser program(argv[0]);

    program.add_argument("n-qubits")
            .default_value(1)
            .action([](const std::string& value) { return std::stoi(value); });
    program.parse_args(argc, argv);
    auto N = program.get<int>("n-qubits");

    auto q = qalloc(N);
    f(q);
    q.print();
}
```

### Implicitly
```C
__qpu__ void f(qreg q) {
  H(q);
  Measure(q);
}

int main(int argc, char** argv) {
    using namespace qcor::arg;

    add_argument("n-qubits")
        .default_value(1)
        .action([](const std::string& value) { return std::stoi(value); });
    parse_args(argc, argv);
    auto N = get_argument<int>("n-qubits");

    auto q = qalloc(N);
    f(q);
    q.print();
}
```

~I thought it was better to expose the ArgumentParser through the `qcor` namespace, so that the program name and version number could be specified. If you would rather this be hidden behind static function calls w/ a global, then let me know and I can rework this a little bit.~

### CODE REVIEW

**Comment by amccaskey** [comment]
hey @amirebrahimi this is great. Thanks for tackling this one. I do have a couple requests: 

I think that argparse is provided as a single header file. I'd prefer if we didn't use git submodules, and instead just added the header file with the project LICENSE to `tpls/argparse/`. 

I also like the idea of enabling one to construct their own `ArgumentParser`, but I think that we would like to see both approaches, the other being the functions delegating to an internal global `ArgumentParser`. Would you mind also adding that? I think you can get away with copying the primary functions on `ArgumentParser` and returning `auto` so we can reproduce the example above. Might also be nice to wrap these functions in `namespace qcor_arg {...}`

**Comment by amirebrahimi** [comment]
Sure thing, @amccaskey. I've updated the PR w/ the changes you requested and edited my top comment with the two ways that you can use it. I added a new namespace `qcor::arg`.

**Comment by amirebrahimi** [comment]
BTW, how does the automagical `using namespace qcor;` make it in for any programs compiled? I ended up having to explicitly state `using namespace qcor::arg` after moving everything into that namespace?

**Comment by amccaskey** [comment]
it's added by the Clang SyntaxHandler https://github.com/ORNL-QCI/qcor/blob/master/handlers/qcor_syntax_handler.cpp#L489

**Comment by amccaskey** [comment]
I think this looks great. I actually prefer that users specify the `arg` namespace to use the API. But the `qcor` namespace is implicitly added by the syntax handler. The only other thing I'd ask on this is that you create an `examples/argparse/` folder and dump your examples in there. Then I think we're good to go.

**Comment by amirebrahimi** [comment]
Added the examples.

**Pull request merged**
